spring:
  security:
    user:
      name: user
      password: $2y$08$mz3KavH5mF5GYICDNl2qouDfAwZOjt.Wvqa0alddg0Mn1cUEgrjk2
  sql:
    init:
      mode: always
  application:
    name: ea-project
  datasource:
    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202303-08;encrypt=true;trustServerCertificate=true;
    username: CS544-202303-08
    password: dc70d089-d5a2-4fb3-b3b9-1e237116fdb7
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
    defer-datasource-initialization: true
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log


